#!/usr/bin/env python3
"""Catalog tooling.

    python scripts/catalog.py validate            # schema + cross-references + CSV parity
    python scripts/catalog.py docs                # docs/modules/CATALOG.md + frontend/src/layers/generated.ts
    python scripts/catalog.py scaffold <module_id> [<module_id> ...]   # write implementation stubs
    python scripts/catalog.py stats               # quick counts

Uses the backend package for the pydantic models, so run it from the backend venv
(`cd backend && uv run python ../scripts/catalog.py validate`) or with the backend installed.
"""

from __future__ import annotations

import csv
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from osint_board.catalog import Catalog, ModuleSpec, load_catalog  # noqa: E402

CATALOG_DIR = ROOT / "catalog"
CSV_PATH = CATALOG_DIR / "osint-modules.csv"
DOC_PATH = ROOT / "docs" / "modules" / "CATALOG.md"
LAYERS_TS = ROOT / "frontend" / "src" / "layers" / "generated.ts"
IMPL_DIR = ROOT / "backend" / "osint_board" / "modules" / "impl"

PHASES = {
    1: "Phase 1 — free APIs and core internal modules",
    2: "Phase 2 — remaining internal modules and external tools",
    3: "Phase 3 — internal replacements for tiered APIs",
    4: "Phase 4 — internal replacements for commercial APIs",
}


def validate(cat: Catalog) -> list[str]:
    errors = cat.reference_errors()
    csv_names = {r["Name"] for r in csv.DictReader(CSV_PATH.open(encoding="utf-8")) if r.get("Name")}
    yaml_names = {m.name for m in cat.modules}
    for missing in sorted(csv_names - yaml_names):
        errors.append(f"CSV row without catalog entry: {missing}")
    for extra in sorted(yaml_names - csv_names):
        errors.append(f"catalog entry without CSV row: {extra}")
    implemented = {p.stem for p in IMPL_DIR.glob("*.py") if p.stem != "__init__"}
    ids = {m.id for m in cat.modules}
    for impl in sorted(implemented - ids):
        errors.append(f"implementation file without catalog entry: {impl}.py")
    return errors


def _md_table(rows: list[list[str]], header: list[str]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(c.replace("|", "\\|") for c in r) + " |" for r in rows]
    return "\n".join(lines)


def docs(cat: Catalog) -> None:
    implemented = {p.stem for p in IMPL_DIR.glob("*.py") if p.stem != "__init__"}
    by_phase: dict[int, list[ModuleSpec]] = defaultdict(list)
    for m in cat.modules:
        by_phase[m.phase].append(m)
    counts = Counter(m.source_type for m in cat.modules)
    status = Counter(m.status for m in cat.modules)

    out = ["# Module catalog", "", "_Generated by `python scripts/catalog.py docs` from `catalog/modules.yaml`. Do not edit by hand._", ""]
    out += ["## Summary", ""]
    out.append(_md_table(
        [[k, str(v)] for k, v in sorted(counts.items())] + [["**total**", f"**{len(cat.modules)}**"]],
        ["Source type (from CSV)", "Modules"],
    ))
    out += ["", _md_table([[k, str(v)] for k, v in sorted(status.items())], ["Verified status", "Modules"]), ""]
    out.append(f"Implemented today: **{len(implemented)}** ({', '.join(sorted(implemented))}).")
    out += ["", "## Globe layers", ""]
    out.append(_md_table(
        [[lyr.id, lyr.name, lyr.group, lyr.render, lyr.update, lyr.color, ", ".join(lyr.sources) or "investigation entities"] for lyr in cat.layers],
        ["id", "name", "group", "render", "update", "colour", "sources"],
    ))
    out += ["", "## Internal replacement services", ""]
    for s in cat.services:
        replaced = cat.modules_replaced_by(s.id)
        out.append(f"### `{s.id}` — {s.name}  (effort {s.effort}, phase {s.phase})")
        out.append("")
        out.append(s.summary)
        out.append("")
        if replaced:
            out.append("Replaces: " + ", ".join(f"`{m.id}`" for m in replaced))
            out.append("")
    for phase, title in PHASES.items():
        mods = sorted(by_phase[phase], key=lambda m: ({"high": 0, "normal": 1, "low": 2}[m.priority], m.category, m.id))
        out += [f"## {title} ({len(mods)} modules)", ""]
        rows = []
        for m in mods:
            flags = []
            if m.id in implemented:
                flags.append("✅ implemented")
            if m.status != "active":
                flags.append(m.status)
            if m.requires_authorization:
                flags.append("⚠ active")
            rows.append([
                f"`{m.id}`", m.name, m.category, m.mode, m.access, m.geo + (f" → {m.layer}" if m.layer else ""),
                ", ".join(m.consumes) or "—", ", ".join(m.replacement) or "—", m.priority, " ".join(flags) or "—",
            ])
        out.append(_md_table(rows, ["id", "name", "category", "mode", "access", "geo", "consumes", "replacement", "priority", "flags"]))
        out.append("")
    out += ["## Notes per module", ""]
    for m in sorted(cat.modules, key=lambda m: m.id):
        if m.notes:
            out.append(f"- **{m.name}** (`{m.id}`): {m.notes}")
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {DOC_PATH.relative_to(ROOT)}")

    ts = [
        "// Generated by `python scripts/catalog.py docs` from catalog/layers.yaml — do not edit.",
        "import type { LayerSpec } from './types';",
        "",
        "export const LAYERS: readonly LayerSpec[] = [",
    ]
    for lyr in cat.layers:
        ts.append("  {")
        ts.append(f"    id: '{lyr.id}',")
        ts.append(f"    name: {lyr.name!r}".replace("'", '"', 0).replace("name: '", "name: '"))
        ts[-1] = f"    name: '{lyr.name.replace(chr(39), chr(92) + chr(39))}',"
        ts.append(f"    group: '{lyr.group}',")
        ts.append(f"    color: '{lyr.color}',")
        ts.append(f"    colorBy: {{ attribute: '{lyr.color_by.attribute}', scale: '{lyr.color_by.scale}' }},")
        ts.append(f"    entityTypes: [{', '.join(repr(str(t)).replace(chr(34), chr(39)) for t in lyr.entity_types)}],")
        ts.append(f"    render: '{lyr.render}',")
        ts.append(f"    update: '{lyr.update}',")
        ts.append(f"    altitude: '{lyr.altitude}',")
        ts.append(f"    defaultVisible: {'true' if lyr.default_visible else 'false'},")
        ts.append(f"    tiled: {'true' if lyr.tiled else 'false'},")
        ts.append(f"    sources: [{', '.join(repr(s).replace(chr(34), chr(39)) for s in lyr.sources)}],")
        ts.append(f"    description: '{lyr.description.replace(chr(39), chr(92) + chr(39))}',")
        ts.append("  },")
    ts += ["];", ""]
    LAYERS_TS.parent.mkdir(parents=True, exist_ok=True)
    LAYERS_TS.write_text("\n".join(ts), encoding="utf-8")
    print(f"wrote {LAYERS_TS.relative_to(ROOT)}")


STUB = '''"""{name} — {description}

Catalog: {id} · {source_type} · {mode} · access={access} · phase {phase}
Consumes: {consumes}
Produces: {produces}
{notes}"""

from __future__ import annotations

from collections.abc import AsyncIterator

from osint_board.entities.types import EntityType
from osint_board.modules.base import {base}
from osint_board.modules.registry import module
from osint_board.modules.types import Emit, EntityRef


@module("{id}")
class {cls}({base}):
    rate_per_sec = 2.0

    async def {method}(self{sig}) -> AsyncIterator[Emit]:
        raise NotImplementedError("see docs/03-module-framework.md")
        yield  # pragma: no cover
'''


def scaffold(cat: Catalog, ids: list[str]) -> None:
    for mid in ids:
        spec = cat.module(mid)
        path = IMPL_DIR / f"{mid}.py"
        if path.exists():
            print(f"skip {path.name} (exists)")
            continue
        base = {"lookup": "LookupModule", "feed": "FeedModule", "extract": "ExtractModule"}[spec.mode]
        method = {"lookup": "lookup", "feed": "poll", "extract": "extract"}[spec.mode]
        sig = {"lookup": ", target: EntityRef", "feed": "", "extract": ", content"}[spec.mode]
        cls = "".join(p.capitalize() for p in mid.split("_"))
        path.write_text(STUB.format(
            name=spec.name, description=spec.description, id=mid, source_type=spec.source_type, mode=spec.mode,
            access=spec.access, phase=spec.phase, consumes=", ".join(spec.consumes) or "—",
            produces=", ".join(spec.produces) or "—", notes=("Notes: " + spec.notes + "\n") if spec.notes else "",
            base=base, cls=cls, method=method, sig=sig,
        ), encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)} — remember to import it in modules/impl/__init__.py")
        _ = EntityType  # keep import referenced for the template


def stats(cat: Catalog) -> None:
    print(f"modules: {len(cat.modules)}")
    for field in ("source_type", "mode", "access", "status", "geo", "phase", "category"):
        c = Counter(getattr(m, field) for m in cat.modules)
        print(f"  {field}: {dict(sorted(c.items(), key=lambda kv: str(kv[0])))}")
    print(f"layers: {len(cat.layers)}  services: {len(cat.services)}  entity types: {len(cat.entities)}")


def main(argv: list[str]) -> int:
    if not argv or argv[0] not in {"validate", "docs", "scaffold", "stats"}:
        print(__doc__)
        return 2
    cat = load_catalog(CATALOG_DIR)
    cmd = argv[0]
    if cmd == "validate":
        errors = validate(cat)
        if errors:
            print("\n".join(errors))
            print(f"\n{len(errors)} problem(s)")
            return 1
        print(f"catalog OK: {len(cat.modules)} modules, {len(cat.layers)} layers, {len(cat.services)} services, {len(cat.entities)} entity types")
        return 0
    if cmd == "docs":
        docs(cat)
        return 0
    if cmd == "scaffold":
        scaffold(cat, argv[1:])
        return 0
    stats(cat)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
